spring:
  codec:
    max-in-memory-size: 10MB
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=Access-Control-Expose-Headers, Authorization
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowed-origins: ${FRONTEND_SERVER}
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS   
            allowed-headers:
              - X-USER-ID
              - X-User-Role
              - X-User-Email
              - X-User-Nickname
              - Content-Type
              - Authorization
              - X-Requested-With
              - Access-Control-Allow-Origin
            allow-credentials: true
            
      routes:
        - id: article
          predicates:
            - Path=/article/**
          uri: lb://ARTICLE
          filters:
            - RewritePath=/article/(?<segment>.*), /${segment}
        - id: authentication
          predicates:
            - Path=/authentication/**
          uri: lb://AUTHENTICATION
          filters:
            - RewritePath=/authentication/(?<segment>.*), /${segment}
        - id: kitcha-board
          predicates:
            - Path=/kitcha-board/**
          uri: lb://KITCHA-BOARD
          filters:
            - RewritePath=/kitcha-board/(?<segment>.*), /${segment}
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

server:
  port: 8072
  forward-headers-strategy: framework

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
